### ISSUE TITLE
Error: Connection is already registered

### ISSUE THREAD

**Issue by jfexyz** [sgress454/sails-hook-autoreload#16]
I've installed this hook, called `sails lift`, and then when I edit a model, I get this error:

```
error: Failed to reinitialize ORM.
error: AdapterError: Connection is already registered
{ [AdapterError: Connection is already registered]
  name: 'AdapterError',
  message: 'Connection is already registered' }
```

Any ideas?

**Comment by sgress454** [comment]
What adapter are you using?

**Comment by jfexyz** [comment]
[Sails Rest](https://github.com/zohararad/sails-rest). Not sure where to begin looking, so thanks!

**Comment by sgress454** [comment]
Looks like the REST adapter needs a `teardown` method.  See the one in [sails-disk](https://github.com/balderdashy/sails-disk/blob/master/lib/adapter.js#L54) for reference.

**Comment by tibotiber** [comment]
Hi! That's a nice hook, thank you :). 
I got the same problem with sails-postgresql v0.10.8. It seems to have a `teardown` method [already implemented](https://github.com/balderdashy/sails-postgresql/blob/0.10.8/lib/adapter.js#L73).
Any idea? Thanks a lot.

**Comment by sgress454** [comment]
@tibotiber Good to know, I'll take a look.

**Comment by gordroid** [comment]
Yeah, awesome hook, really useful!
Same here, with sails-redis 0.10.3 ;D teardown is implemented as well.
I'll take a look what's going on, and send a PR if i can fix the issue.
Thanks!

**Comment by thomasfr** [comment]
same error here with sails 0.11 and these adapters:

```
"sails-mongo": "0.11.2",
"sails-postgresql": "0.10.15",
"sails-redis": "0.10.4",
```

```
verbose: Detected API change -- reloading controllers / models...
verbose: Loading the app's models and adapters...
verbose: Loading app models...
verbose: Loading app adapters...
verbose: Starting ORM...
error: Failed to reinitialize ORM.
error: Error: Connection is already registered
    at Object.module.exports.adapter.registerConnection (/Users/thomas/example/node_modules/sails-redis/lib/adapter.js:65:54)
    at /Users/thomas/exmaple/node_modules/sails/node_modules/waterline/lib/waterline.js:203:29
    at /Users/thomas/example/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:162:20
    at /Users/thomas/example/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:230:13
    at _arrayEach (/Users/thomas/example/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at _each (/Users/thomas/example/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:72:13)
    at Object.async.forEachOf.async.eachOf (/Users/thomas/example/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:229:9)
    at Object.async.forEach.async.each (/Users/thomas/example/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:206:22)
    at Array.async.auto.registerConnections (/Users/thomas/example/node_modules/sails/node_modules/waterline/lib/waterline.js:176:13)
    at /Users/thomas/example/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:590:38
    at _arrayEach (/Users/thomas/example/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:81:9)
    at Object.async.auto (/Users/thomas/example/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:552:9)
    at Waterline.initialize (/Users/thomas/example/node_modules/sails/node_modules/waterline/lib/waterline.js:121:9)
    at buildORM (/Users/thomas/example/node_modules/sails/lib/hooks/orm/build-orm.js:52:15)
    at Array.async.auto.instantiatedCollections (/Users/thomas/example/node_modules/sails/lib/hooks/orm/index.js:203:11)
    at listener (/Users/thomas/example/node_modules/sails/node_modules/async/lib/async.js:490:46) [Error: Connection is already registered]
```

**Comment by ronenteva** [comment]
Same here with sails-redis

**Comment by ali-pourzahmatkesh** [comment]
same with sails-mysql !

**Comment by sgress454** [comment]
I can't recreate this on sails v0.11.x with sails-mysql, sails-postgresql or sails-mongo.  Tried it with a new app with a User model and controller.  Seems like something else is contributing to the issue--does anyone on this thread have a public project I can clone to try and get to the bottom of it?

**Comment by element4git** [comment]
Try sails-redis

It works well for the other connections.

**Comment by KirillSuhodolov** [comment]
@element4git @sgress454 sails-postgresql - fixed, but sails-redis breaks

**Comment by davemackintosh** [comment]
This is still an issue with `sails-memory`, will look to PR if the `teardown` isn't implemented as it's messing with some tests of mine.

**Comment by Oldwo1f** [comment]
I got the same problem with `sails-elasticsearch`.

It seams to have the teardown method implemented but i still go this error 

> Connection is already registered

**Comment by Fr33maan** [comment]
Well, what I can say from my experience is that sails-hook-autoreload and sails-webpack are compatible under certain conditions which are not clear yet for me.
I initially had this issue but managed to get rid of it.

[The repo with the issue](https://github.com/l1br3/sails-webpack-react) (clone the react branch)
[The repo without the issue](https://github.com/l1br3/sails-webpack-react-2)

**Comment by Fr33maan** [comment]
Same king of issue there https://github.com/sgress454/sails-hook-autoreload/issues/60
