### ISSUE TITLE
Sails crash if Many-to-Many associations present

### ISSUE THREAD

**Issue by firebull** [sgress454/sails-hook-autoreload#28]
Strange issue with MySQL adapter, sails-hook-autoreload and Many-to-Many associations.

**Model Boys.js**

``` javascript
module.exports = {
    connection: 'testMysqlServer',
    attributes: {
        id: {
              type: 'integer',
              primaryKey: true,
              autoIncrement: true,
              unique: true
          },
        name: { type: 'string',
              required: true
            },
        girls: {
            collection: 'girls',
            via: 'boys'
        },
  }
};
```

**Model Girls.js**

``` javascript
module.exports = {
    connection: 'testMysqlServer',
    attributes: {
        id: {
              type: 'integer',
              primaryKey: true,
              autoIncrement: true,
              unique: true
          },
        name: { type: 'string',
              required: true
            },
        boys: {
            collection: 'boys',
            via: 'girls'
        },
  }
};
```

So after `sails lift` everything works fine. But when save any changes to any monitored by _sails-hook-autoreload_ I got an exception and crush:

```
/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/helpers.js:70
  return hop.call(obj, prop);
             ^
TypeError: Cannot convert null to object
    at hasOwnProperty (native)
    at exports.object.hasOwnProperty (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/helpers.js:70:14)
    at Core._normalizeSchemaFlag (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/index.js:142:6)
    at module.exports (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/core/index.js:44:46)
    at module.exports (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/collection/index.js:44:8)
    at new child (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/extend.js:17:39)
    at new bound (/usr/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:726:29)
    at initialize (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline/collection/loader.js:37:10)
    at loadCollection (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:112:29)
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/usr/lib/node_modules/sails/node_modules/async/lib/async.js:124:9)
    at Array.async.auto.loadCollections [as 0] (/usr/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:125:13)
    at /usr/lib/node_modules/sails/node_modules/async/lib/async.js:487:38
    at Array.forEach (native)
```

After new start everything works. I reproduced this error on new and clean Sails installation. There is no such error with Sails-disk DB. May be this issue must be published to Waterline issues, but it occures only on reload by _sails-hook-autoreload_.

**Comment by firebull** [comment]
Issue is fixed in Waterline.
