### ISSUE TITLE
AdapterError after updating

### ISSUE THREAD

**Issue by moisesrodriguez** [sgress454/sails-hook-autoreload#41]
sails-hook-autoreload is crashing every time after I make an update

```
2015-10-04, 8:18:10 pm - verbose: Detected API change -- reloading controllers / models...
2015-10-04, 8:18:10 pm - verbose: Loading the app's models and adapters...
2015-10-04, 8:18:10 pm - verbose: Loading app models...
2015-10-04, 8:18:10 pm - verbose: Loading app adapters...
2015-10-04, 8:18:10 pm - verbose: Lowering sails...
2015-10-04, 8:18:10 pm - verbose: Shutting down socket server...
2015-10-04, 8:18:10 pm - verbose: Shutting down HTTP server...
/Users/moises/web/backend/node_modules/sails-mysql/lib/adapter.js:58
      if (evName === 'error') { throw data; }
                                ^

AdapterError: Invalid connection name specified
    at getConnectionObject (/Users/moises/web/backend/node_modules/sails-mysql/lib/adapter.js:1182:35)
    at spawnConnection (/Users/moises/web/backend/node_modules/sails-mysql/lib/adapter.js:1097:7)
    at Object.module.exports.adapter.describe (/Users/moises/web/backend/node_modules/sails-mysql/lib/adapter.js:115:16)
    at module.exports.describe (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/adapter/ddl/index.js:80:13)
    at module.exports [as migrateAlter] (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/alter.js:34:8)
    at Query.sync (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:68:37)
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline.js:288:16
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:162:20
    at iterate (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:256:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:275:9)
    at Object.async.forEachSeries.async.eachSeries (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:211:22)
    at bootstrap (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline.js:286:9)
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline.js:212:10
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:49:16
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:548:17
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:542:17
```

I'm using Node 4.1.1, Sails 11.2, sails-hook-autoreload 0.12.0

**Comment by moisesrodriguez** [comment]
Very weird how sails-hook-autoreload is working. I noticed that if I change a tab in Atom editor, it will reload (but not crash). I changed to Visual Studio Code and I don't get the weird auto-reload when changing tabs. Still crashing after changing a file. The errors keep changing, here is a couple

```
2015-10-06, 5:27:59 pm - verbose: Detected API change -- reloading controllers / models...
2015-10-06, 5:27:59 pm - verbose: Loading the app's models and adapters...
2015-10-06, 5:27:59 pm - verbose: Loading app models...
2015-10-06, 5:27:59 pm - verbose: Loading app adapters...
2015-10-06, 5:27:59 pm - error: Failed to reinitialize ORM.
2015-10-06, 5:27:59 pm - error: Error (E_UNKNOWN) :: Encountered an unexpected error
: Cannot enqueue Query after invoking quit.
    at Protocol._validateEnqueue (/Users/moises/web/backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:196:16)
    at Protocol._enqueue (/Users/moises/web/backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:129:13)
    at PoolConnection.Connection.query (/Users/moises/web/backend/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:185:25)
    at Query.__DESCRIBE__ [as _callback] (/Users/moises/web/backend/node_modules/sails-mysql/lib/adapter.js:144:22)
    at Query.Sequence.end (/Users/moises/web/backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/Users/moises/web/backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/Users/moises/web/backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/Users/moises/web/backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/moises/web/backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/moises/web/backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/moises/web/backend/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:82:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

Details:  Error: Cannot enqueue Query after invoking quit.

2015-10-06, 5:27:59 pm - verbose: Lowering sails...
2015-10-06, 5:27:59 pm - verbose: Shutting down socket server...
2015-10-06, 5:27:59 pm - verbose: Shutting down HTTP server...
/Users/moises/web/backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
        ^

Error: [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Cannot enqueue Query after invoking quit.

    at /Users/moises/web/backend/node_modules/sails/lib/hooks/orm/index.js:221:19
    at taskCallback (/Users/moises/web/backend/node_modules/async/lib/async.js:471:21)
    at /Users/moises/web/backend/node_modules/sails/lib/hooks/orm/build-orm.js:57:23
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline.js:213:22
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:49:16
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:258:21
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:40:16
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:69:22
    at afterDescribe (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/alter.js:36:20)
    at wrapper (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:331:16)
    at callback.error (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:46:28)
    at sendBackError (/Users/moises/web/backend/node_modules/sails-mysql/lib/connections/spawn.js:91:11)
    at Object.module.exports.poolfully [as releaseConnection] (/Users/moises/web/backend/node_modules/sails-mysql/lib/connections/release.js:28:12)
```

```
2015-10-06, 5:32:26 pm - verbose: Detected API change -- reloading controllers / models...
2015-10-06, 5:32:26 pm - verbose: Loading the app's models and adapters...
2015-10-06, 5:32:26 pm - verbose: Loading app models...
2015-10-06, 5:32:27 pm - verbose: Loading app adapters...
2015-10-06, 5:32:27 pm - verbose: Starting ORM...
2015-10-06, 5:32:27 pm - verbose: Detected API change -- reloading controllers / models...
2015-10-06, 5:32:27 pm - verbose: Loading the app's models and adapters...
2015-10-06, 5:32:27 pm - verbose: Loading app models...
2015-10-06, 5:32:27 pm - verbose: Loading app adapters...
Waterline encountered a fatal error when trying to perform the `alter` auto-migration strategy.
In a couple of seconds, the data (cached in memory) will be logged to stdout.
(a failsafe put in place to preserve development data)

In the mean time, here's the error:

Error (E_UNKNOWN) :: Encountered an unexpected error
: Could not connect to MySQL:
Error: Pool is closed.
    at afterwards (/Users/moises/web/backend/node_modules/sails-mysql/lib/connections/spawn.js:72:13)
    at /Users/moises/web/backend/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at doNTCallback0 (node.js:408:9)
    at process._tickDomainCallback (node.js:378:13)

Details:  Error: Could not connect to MySQL:
Error: Pool is closed.



2015-10-06, 5:32:27 pm - verbose: Starting ORM...
================================
Data backup:
================================

[]
2015-10-06, 5:32:28 pm - error: Failed to reinitialize ORM.
2015-10-06, 5:32:28 pm - error: Error (E_UNKNOWN) :: Encountered an unexpected error
: Could not connect to MySQL:
Error: Pool is closed.
    at afterwards (/Users/moises/web/backend/node_modules/sails-mysql/lib/connections/spawn.js:72:13)
    at /Users/moises/web/backend/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at doNTCallback0 (node.js:408:9)
    at process._tickDomainCallback (node.js:378:13)

Details:  Error: Could not connect to MySQL:
Error: Pool is closed.

2015-10-06, 5:32:28 pm - verbose: Lowering sails...
2015-10-06, 5:32:28 pm - verbose: Shutting down socket server...
2015-10-06, 5:32:28 pm - verbose: Shutting down HTTP server...
/Users/moises/web/backend/node_modules/sails/lib/hooks/orm/index.js:221
            throw new Error(err);
            ^

Error: [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Could not connect to MySQL:
Error: Pool is closed.

    at /Users/moises/web/backend/node_modules/sails/lib/hooks/orm/index.js:221:19
    at taskCallback (/Users/moises/web/backend/node_modules/async/lib/async.js:471:21)
    at /Users/moises/web/backend/node_modules/sails/lib/hooks/orm/build-orm.js:57:23
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline.js:213:22
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:49:16
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:258:21
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:40:16
    at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/query/index.js:69:22
    at null._onTimeout (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/adapter/sync/strategies/alter.js:279:12)
    at Timer.listOnTimeout (timers.js:89:15)
```

**Comment by sgress454** [comment]
@moisesrodriguez Are you connecting to a remote database?  Can you share your Sails connection config (without the password of course)?

**Comment by moisesrodriguez** [comment]
@sgress454 I stopped using this hook after those errors. I don't remember if when I had those errors if I was connecting to a remote database, but probably was because once in a while I do connect to my remote database.

my config for the remote database looks like this 

```
mysql: {
      adapter: 'sails-mysql',
      host: 'url-to-remote',
      user: 'sample',
      password: 'sample',
      database: 'sample',
      charset: 'utf8',
      collation: 'utf8_spanish_ci'
    }
```

I can try again this hook see if the problems persist, but I do remember it was very annoying that when in my text editor (Atom) when I changed tabs the hook would see that as file change and it would reload sails.

**Comment by semy** [comment]
same error, i will kick the hook, can't work :-(

**Comment by t-wee** [comment]
+1

**Comment by sgress454** [comment]
Sorry all, there's not really much to go on here.  This hook is intended to ease development in basic environments; it's impossible to provide support for every remote database out there (and I would argue that developing against a remote database is a bad idea anyway--makes debugging kind of opaque).  If the database reload is giving you trouble, try setting `sails.config.migrate` to `"safe"` in your `config/models.js` and set `sails.config.autoreload.overrideMigrateSetting` to `false` in your `config/development.js`.

**Comment by HaiderMalik12** [comment]
Same error here
