### ISSUE TITLE
Waterline encountered a fatal error when trying to perform the `alter` auto-migration strategy.

### ISSUE THREAD

**Issue by juanpasolano** [sgress454/sails-hook-autoreload#44]
Every time I change something in a controller and the hooks restarts the ORM I get this error.
The thing i don't get is why is trying to migrate if I have `migrate: 'safe'` in my `config/models.js`

```
verbose: Detected API change -- reloading controllers / models...
verbose: Loading the app's models and adapters...
verbose: Loading app models...
verbose: Loading app adapters...
verbose: Starting ORM...
Waterline encountered a fatal error when trying to perform the `alter` auto-migration strategy.
In a couple of seconds, the data (cached in memory) will be logged to stdout.
(a failsafe put in place to preserve development data)

In the mean time, here's the error:

Error (E_UNKNOWN) :: Encountered an unexpected error
: ER_NO_SUCH_TABLE: Table 'vetheroes.branch' doesn't exist
    at Query.Sequence._packetToError (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:92:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
    --------------------
    at Protocol._enqueue (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at PoolConnection.Connection.query (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:197:25)
    at /Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/lib/adapter.js:489:22
    at /Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/async/lib/async.js:154:25
    at Query._callback (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/lib/adapter.js:464:13)
    at Query.Sequence.end (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.OkPacket (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:78:10)
    at Protocol._parsePacket (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/juan/Documents/juanpa/vetapp/sites/webapp/back/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:92:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

Details:  Error: ER_NO_SUCH_TABLE: Table 'vetheroes.branch' doesn't exist
```

sails v.11

**Comment by juanpasolano** [comment]
I see this PR and it kind of makes sense, right?
https://github.com/sgress454/sails-hook-autoreload/pull/43

**Comment by akmoulai** [comment]
I have the same issue. I think our issue won't be fixed by #43 as it sets migrate to `alter` by default.

I'd suggest to guard L70 with something like:

```
        // don't drop database
        if (sails.config.models.migrate == 'drop') {
          sails.config.models.migrate = 'alter';
        }
```

Users with a `migrate: 'safe'` strategy would not be impacted.

**Comment by juanpasolano** [comment]
Yes I agree. It should depend on `sails.config.models.migrate` configuration.

**Comment by westito** [comment]
+1

**Comment by tommykennedy** [comment]
+1

**Comment by misterGF** [comment]
+1

**Comment by sgress454** [comment]
Thanks for the feedback everyone.  Just published v0.13.0 which includes the `overrideMigrateSetting`.  Set it to `false` to use your app's migrate setting instead of having the hook override it to `alter`.

**Comment by dv336699** [comment]
I think it's too dangerous to have set this set as true by default?
It took me a bit to find this issue as to why my app was breaking even after setting to "safe" in my sails.config.models.migrate - using sails-mysql

```
Waterline encountered a fatal error when trying to perform the `alter` auto-migration strategy.
In a couple of seconds, the data (cached in memory) will be logged to stdout.
(a failsafe put in place to preserve development data)

In the mean time, here's the error:

Error (E_UNKNOWN) :: Encountered an unexpected error
: ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails
    at Query.Sequence._packetToError (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
    --------------------
    at Protocol._enqueue (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:201:25)
    at dropTable (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/lib/adapter.js:275:22)
    at /Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/lib/adapter.js:287:11
    at /Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/async/lib/async.js:52:16
    at iterate (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/async/lib/async.js:260:24)
    at Object.async.forEachOfSeries.async.eachOfSeries (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/async/lib/async.js:214:22)
    at __DROP__ (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/lib/adapter.js:285:15)
    at afterwards (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/lib/connections/spawn.js:84:5)
    at /Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Ping.onOperationComplete [as _callback] (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:99:5)
    at Ping.Sequence.end (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Ping.Sequence.OkPacket (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/diego/Qsync/Projects/sailsjs/pvi/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)

Details:  Error: ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails

```

**Comment by fjafferi** [comment]
+1

**Comment by sgress454** [comment]
> I think it's too dangerous to have set this set as true by default?

Only as dangerous as not reading the README, which make it very clear that a) this hook is not intended for use in production (so there should no danger of losing important data) and b) that the migrate strategy is set to `alter` by default.  For the kind of development for which this hook is intended, using `migrate: safe` is sort of pointless: your changes wouldn't actually be reloaded.
