### ISSUE TITLE
Fails on updating the code 

### ISSUE THREAD

**Issue by basilinjoe** [sgress454/sails-hook-autoreload#57]
/home/xcz/sails/facebook-auth/node_modules/sails-hook-autoreload/index.js:103
        sails.hooks.controllers.loadAndRegisterControllers(function() {
                                ^
TypeError: Object #<Hook> has no method 'loadAndRegisterControllers'
    at FSWatcher.<anonymous> (/home/xcz/sails/facebook-auth/node_modules/sails-hook-autoreload/index.js:103:33)
    at complete (/home/xcz/.npm-global/lib/node_modules/sails/node_modules/lodash/index.js:7697:25)
    at delayed [as _onTimeout](/home/xcz/.npm-global/lib/node_modules/sails/node_modules/lodash/index.js:7707:11)
    at Timer.listOnTimeout [as ontimeout](timers.js:112:15)

**Comment by sgress454** [comment]
You need to install Sails v0.12.1.  See https://github.com/sgress454/sails-hook-autoreload/issues/53.
