### ISSUE TITLE
sails.reloadActions is not a function

### ISSUE THREAD

**Issue by fortil** [sgress454/sails-hook-autoreload#70]
Hi guys

I have a problem, when auto-reload detect a change the server broken. these is the message.
```
sails> verbose: sails-hook-autoreload: Detected API change -- reloading controllers / models...
verbose: Lowering sails...
C:\Users\user\Documents\back\node_modules\sails-hook-autoreload\index.js:88
        sails.reloadActions(function() {
              ^

TypeError: sails.reloadActions is not a function
    at FSWatcher.<anonymous> (C:\Users\user\Documents\back\node_modules\sails-hook-autoreload\index.js:88:15)
    at complete (C:\Users\user\Documents\back\node_modules\@sailshq\lodash\lib\index.js:7873:25)
    at Timeout.delayed [as _onTimeout] (C:\Users\user\Documents\back\node_modules\@sailshq\lodash\lib\index.js:7883:11)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
What can I do?
Thanks

**Comment by arvinddhasmana** [comment]
I am facing the same issue.

**Comment by anyIris** [comment]
+1

**Comment by sgress454** [comment]
The newest version of the hook is only compatible with Sails v1.0.  To install the hook for Sails v0.12.x, do `npm install sails-hook-autoreload@for-sails-0.12`.  Sorry about that, I'll go ahead and update the README.

**Comment by fortil** [comment]
Thanks

But now, I have the next problem
```

sails.router.explicitRoutes = _.omit(sails.router.explicitRoutes, function(action, address) {
                                ^

TypeError: Cannot read property 'omit' of undefined
    at Sails.<anonymous> (C:\Users\user\Documents\back\node_modules\sails-hook-autoreload\index.js:130:44)
    at Sails.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Sails.emit (events.js:185:7)
    at Sails.emitter.emit (C:\Users\user\Documents\back\node_modules\sails\lib\app\private\after.js:50:11)
    at C:\Users\user\Documents\back\node_modules\sails-hook-orm\lib\reload.js:40:13
    at C:\Users\user\Documents\back\node_modules\sails-hook-orm\node_modules\async\lib\async.js:52:16
    at C:\Users\user\Documents\back\node_modules\sails-hook-orm\node_modules\async\lib\async.js:550:17
    at C:\Users\user\Documents\back\node_modules\sails-hook-orm\node_modules\async\lib\async.js:544:17
    at _arrayEach (C:\Users\user\Documents\back\node_modules\sails-hook-orm\node_modules\async\lib\async.js:85:13)
```

I think so this problem is for lodash, but, what have I to do?

Edited:

I agree:
```
var _ = {
  omit: require('lodash/omit'),
  extend: require('lodash/extend')
};
```
In index.js file..

**Comment by sgress454** [comment]
Ah, thanks @fortil.  It looks like I didn't add Lodash as a dependency -- the hook should still work if you have global Lodash enabled in your Sails app (i.e. in `config/globals.js`), but as of sails-hook-autoreload@0.14.1 (just published) it should work with globals turned off as well.
