### ISSUE TITLE
reload fails

### ISSUE THREAD

**Issue by greggreenhaw** [sgress454/sails-hook-autoreload#73]
Running sails lift works fine, however if I save a change and rerun an api request I get this error:

TypeError: Model.findOne is not a function
    at Object.findOneRecord (node_modules/sails/lib/hooks/blueprints/actions/findOne.js:35:4)
    at node_modules/sails/lib/router/bind.js:218:42
    at routeTargetFnWrapper (node_modules/sails/lib/router/bind.js:350:9)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at next (node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at node_modules/express/lib/router/index.js:281:22
    at param (node_modules/express/lib/router/index.js:354:14)
    at param (node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (node_modules/express/lib/router/index.js:410:3)
    at next (node_modules/express/lib/router/index.js:275:10)
    at next (node_modules/express/lib/router/route.js:127:14)
    at Hook.expressMiddleware (node_modules/sails/lib/hooks/i18n/index.js:191:14)
    at Hook.wrapper [as expressMiddleware] (node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at addLocalizationMethod (node_modules/sails/lib/hooks/i18n/index.js:136:35)
    at routeTargetFnWrapper (node_modules/sails/lib/router/bind.js:350:9)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at next (node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at node_modules/express/lib/router/index.js:281:22

**Comment by sgress454** [comment]
@greggreenhaw  Thanks for using Sails!  We've decided to end official support for this hook, as detailed in the [end-of-life notice](https://github.com/sgress454/sails-hook-autoreload#skull-skull-skull-official-end-of-life-notice-skull-skull-skull).  If you're interested in taking over, please contact [@sgress454](@sgress454).

**Comment by Fr33maan** [comment]
Reproduction repo please
