### ISSUE TITLE
Possible incompatibility with sails-postgresql

### ISSUE THREAD

**Issue by siderlan** [sgress454/sails-hook-autoreload#85]
Hi,

I'm using sails 1.0.2 and sails-postgresql 1.0.1. So when it tries to reload the server an exception has been thrown in module parley/lib/private/Deferred.js:313 with the following stack trace:

Error: Callback was already called.
    at /my-project/node_modules/async/dist/async.js:844:36
    at /my-project/sails-hook-orm/lib/initialize.js:457:27
    at /my-project/node_modules/sails-hook-orm/lib/build-ontology-and-run-auto-migrations.js:133:25
    at afterMigrate (/my-project/node_modules/waterline-utils/lib/auto-migrations/private/run-alter-strategy/index.js:209:14)
    at /my-project/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/my-project/node_modules/async/dist/async.js:995:17)
    at /my-project/node_modules/async/dist/async.js:847:20
    at findCallback (/my-project/node_modules/waterline-utils/lib/auto-migrations/private/run-alter-strategy/index.js:116:18)
    at proceedToFinalAfterExecLC (/my-project/node_modules/parley/lib/private/Deferred.js:1179:16)
    at proceedToInterceptsAndChecks (/my-project/node_modules/parley/lib/private/Deferred.js:909:12)
    at proceedToAfterExecSpinlocks (/my-project/node_modules/parley/lib/private/Deferred.js:841:10)
    at /my-project/node_modules/parley/lib/private/Deferred.js:303:7
    at Deferred._.extend._WLModel [as _handleExec] (/my-project/node_modules/waterline/lib/waterline/methods/find.js:214:20)
    at Deferred.exec (/my-project/node_modules/parley/lib/private/Deferred.js:286:10)
    at simultaneouslyMigrateEachModel (/my-project/node_modules/waterline-utils/lib/auto-migrations/private/run-alter-strategy/index.js:95:6)
    at /my-project/node_modules/async/dist/async.js:3047:20
    at eachOfArrayLike (/my-project/node_modules/async/dist/async.js:1002:13)
    at eachOf (/my-project/node_modules/async/dist/async.js:1052:9)
    at Object.eachLimit (/my-project/node_modules/async/dist/async.js:3111:7)
    at runAlterStrategy (/my-project/node_modules/waterline-utils/lib/auto-migrations/private/run-alter-strategy/index.js:40:9)
    at Object.runAutoMigrations [as autoMigrations] (/my-project/node_modules/waterline-utils/lib/auto-migrations/index.js:45:19)
    at _afterInitializingWaterline (/my-project/node_modules/sails-hook-orm/lib/build-ontology-and-run-auto-migrations.js:132:20)
    at /my-project/node_modules/waterline/lib/waterline.js:722:14
    at /my-project/node_modules/async/dist/async.js:952:25
    at iteratorCallback (/my-project/node_modules/async/dist/async.js:997:17)
    at /my-project/node_modules/async/dist/async.js:847:20
    at Immediate.done (/my-project/node_modules/sails-postgresql/lib/adapter.js:71:16)
    at runCallback (timers.js:763:18)

**Comment by tikijian** [comment]
+1

**Comment by prcs** [comment]
MySQL too

**Comment by elesdoar** [comment]
This is partial solution, but for fix it, disable `archiveModelIdentity` model setting.

https://sailsjs.com/documentation/reference/configuration/sails-config-models
