### ISSUE TITLE
win10os sails.js 1.1.0 not work.

### ISSUE THREAD

**Issue by ncc0706** [sgress454/sails-hook-autoreload#89]
**package.json**
``` json
{
  "name": "sails-demo-app",
  "private": true,
  "version": "0.0.0",
  "description": "a Sails application",
  "keywords": [],
  "dependencies": {
    "@sailshq/connect-redis": "^3.2.1",
    "@sailshq/lodash": "^3.10.3",
    "@sailshq/socket.io-redis": "^5.2.0",
    "grunt": "1.0.1",
    "sails": "^1.1.0",
    "sails-hook-autoreload": "^1.1.0",
    "sails-hook-grunt": "^3.1.0",
    "sails-hook-orm": "^2.1.1",
    "sails-hook-sockets": "^1.5.5",
    "sails-mongo": "1.0.1"
  },
  "devDependencies": {
    "@sailshq/eslint": "^4.19.3"
  },
  "scripts": {
    "start": "NODE_ENV=production node app.js",
    "test": "npm run lint && npm run custom-tests && echo 'Done.'",
    "lint": "eslint . --max-warnings=0 --report-unused-disable-directives && echo '✔  Your .js files look good.'",
    "custom-tests": "echo \"(No other custom tests yet.)\" && echo"
  },
  "main": "app.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/anonymous node/sails user/sails-demo-app.git"
  },
  "author": "anonymous node/sails user",
  "license": "",
  "engines": {
    "node": "^10.13"
  }
}

```
**error**
```
 info: ·• Auto-migrating...  (alter)
 info:    Hold tight, this could take a moment.
 warn: Ignored attempt to bind route (/archive/find) to unknown action :: archive/find
 warn: Ignored attempt to bind route (/archive/find/:id) to unknown action :: archive/findOne
 warn: Ignored attempt to bind route (/archive/create) to unknown action :: archive/create
 warn: Ignored attempt to bind route (/archive/update/:id) to unknown action :: archive/update
 warn: Ignored attempt to bind route (/archive/destroy/:id) to unknown action :: archive/destroy
 warn: Ignored attempt to bind route (/archive) to unknown action :: archive/find
 warn: Ignored attempt to bind route (/archive/:id) to unknown action :: archive/findOne
 warn: Ignored attempt to bind route (/archive) to unknown action :: archive/create
 warn: Ignored attempt to bind route (/archive/:id) to unknown action :: archive/update
 warn: Ignored attempt to bind route (/archive/:id?) to unknown action :: archive/destroy
 warn: Ignored attempt to bind route (/archive/:id) to unknown action :: archive/update
E:\2019\nodejs\sails-demo-app\node_modules\parley\lib\private\Deferred.js:313
      throw e.raw;
      ^

Error: Callback was already called.
    at E:\2019\nodejs\sails-demo-app\node_modules\sails-hook-orm\node_modules\async\dist\async.js:844:36
    at E:\2019\nodejs\sails-demo-app\node_modules\sails-hook-orm\lib\initialize.js:457:27
    at E:\2019\nodejs\sails-demo-app\node_modules\sails-hook-orm\lib\build-ontology-and-run-auto-migrations.js:133:25
    at afterMigrate (E:\2019\nodejs\sails-demo-app\node_modules\waterline-utils\lib\auto-migrations\private\run-alter-strategy\index.js:209:14)
    at E:\2019\nodejs\sails-demo-app\node_modules\waterline-utils\node_modules\async\dist\async.js:952:25
    at iteratorCallback (E:\2019\nodejs\sails-demo-app\node_modules\waterline-utils\node_modules\async\dist\async.js:995:17)
    at E:\2019\nodejs\sails-demo-app\node_modules\waterline-utils\node_modules\async\dist\async.js:847:20
    at findCallback (E:\2019\nodejs\sails-demo-app\node_modules\waterline-utils\lib\auto-migrations\private\run-alter-strategy\index.js:116:18)
    at proceedToFinalAfterExecLC (E:\2019\nodejs\sails-demo-app\node_modules\parley\lib\private\Deferred.js:1179:16)
    at proceedToInterceptsAndChecks (E:\2019\nodejs\sails-demo-app\node_modules\parley\lib\private\Deferred.js:909:12)
    at proceedToAfterExecSpinlocks (E:\2019\nodejs\sails-demo-app\node_modules\parley\lib\private\Deferred.js:841:10)
    at E:\2019\nodejs\sails-demo-app\node_modules\parley\lib\private\Deferred.js:303:7
    at Deferred._.extend._WLModel [as _handleExec] (E:\2019\nodejs\sails-demo-app\node_modules\waterline\lib\waterline\methods\find.js:214:20)
    at Deferred.exec (E:\2019\nodejs\sails-demo-app\node_modules\parley\lib\private\Deferred.js:286:10)
    at simultaneouslyMigrateEachModel (E:\2019\nodejs\sails-demo-app\node_modules\waterline-utils\lib\auto-migrations\private\run-alter-strategy\index.js:95:6)
    at E:\2019\nodejs\sails-demo-app\node_modules\waterline-utils\node_modules\async\dist\async.js:3047:20

```

**Comment by ncc0706** [comment]
config/models.js add ``archiveModelIdentity: false``
